apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomalies-backend
  labels:
    app: anomalies-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomalies-backend
  template:
    metadata:
      labels:
        app: anomalies-backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: anomalies-backend
          image: #{image}#
          env:
          - name: NODE_ENV
            value: #{env}#
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "80m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: anomalies-backend
  labels:
    app: anomalies-backend
spec:
  selector:
    app: anomalies-backend
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
