name: Deploy

env:
  NODE_ENV: development
  PORT: 3000
  LOG_DIR: ../../logs
  LOG_FORMAT: combined
  ORIGIN: '*'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "validator-anomalies"
          email: "manwkult@gmail.com"
